//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/MainProject/Resources/NoteClick.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/MainProject/Resources/NoteClick.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @NoteClick: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @NoteClick()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""NoteClick"",
    ""maps"": [
        {
            ""name"": ""NoteClickMap"",
            ""id"": ""4aa4dfcb-8ebe-4511-9c7a-103cd7233ee3"",
            ""actions"": [
                {
                    ""name"": ""NoteClick1"",
                    ""type"": ""Button"",
                    ""id"": ""b5375118-0dfc-4510-bd8a-12da6dce6d1a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NoteClick2"",
                    ""type"": ""Button"",
                    ""id"": ""f97c7ea2-2d58-488d-9127-6950ae5e981f"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NoteClick3"",
                    ""type"": ""Button"",
                    ""id"": ""62d35d5e-1286-47a0-9069-c2769184d1e2"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""NoteClick4"",
                    ""type"": ""Button"",
                    ""id"": ""fcf8cfbe-20ea-4ee4-ab49-eea607f62e5e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""6e46a19e-4f81-4b4a-acc9-71f1e1dccfc9"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoteClick1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38c77cda-b9d1-4ff1-b1b3-2cf76e6dace7"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoteClick2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""26356581-c8c6-41ed-9d39-5f10193ed9da"",
                    ""path"": ""<Keyboard>/l"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoteClick3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b30b9a5-a448-4ad7-b684-0beaa8379f9a"",
                    ""path"": ""<Keyboard>/semicolon"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""NoteClick4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""PC"",
            ""bindingGroup"": ""PC"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // NoteClickMap
        m_NoteClickMap = asset.FindActionMap("NoteClickMap", throwIfNotFound: true);
        m_NoteClickMap_NoteClick1 = m_NoteClickMap.FindAction("NoteClick1", throwIfNotFound: true);
        m_NoteClickMap_NoteClick2 = m_NoteClickMap.FindAction("NoteClick2", throwIfNotFound: true);
        m_NoteClickMap_NoteClick3 = m_NoteClickMap.FindAction("NoteClick3", throwIfNotFound: true);
        m_NoteClickMap_NoteClick4 = m_NoteClickMap.FindAction("NoteClick4", throwIfNotFound: true);
    }

    ~@NoteClick()
    {
        UnityEngine.Debug.Assert(!m_NoteClickMap.enabled, "This will cause a leak and performance issues, NoteClick.NoteClickMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // NoteClickMap
    private readonly InputActionMap m_NoteClickMap;
    private List<INoteClickMapActions> m_NoteClickMapActionsCallbackInterfaces = new List<INoteClickMapActions>();
    private readonly InputAction m_NoteClickMap_NoteClick1;
    private readonly InputAction m_NoteClickMap_NoteClick2;
    private readonly InputAction m_NoteClickMap_NoteClick3;
    private readonly InputAction m_NoteClickMap_NoteClick4;
    /// <summary>
    /// Provides access to input actions defined in input action map "NoteClickMap".
    /// </summary>
    public struct NoteClickMapActions
    {
        private @NoteClick m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public NoteClickMapActions(@NoteClick wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "NoteClickMap/NoteClick1".
        /// </summary>
        public InputAction @NoteClick1 => m_Wrapper.m_NoteClickMap_NoteClick1;
        /// <summary>
        /// Provides access to the underlying input action "NoteClickMap/NoteClick2".
        /// </summary>
        public InputAction @NoteClick2 => m_Wrapper.m_NoteClickMap_NoteClick2;
        /// <summary>
        /// Provides access to the underlying input action "NoteClickMap/NoteClick3".
        /// </summary>
        public InputAction @NoteClick3 => m_Wrapper.m_NoteClickMap_NoteClick3;
        /// <summary>
        /// Provides access to the underlying input action "NoteClickMap/NoteClick4".
        /// </summary>
        public InputAction @NoteClick4 => m_Wrapper.m_NoteClickMap_NoteClick4;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_NoteClickMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="NoteClickMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(NoteClickMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="NoteClickMapActions" />
        public void AddCallbacks(INoteClickMapActions instance)
        {
            if (instance == null || m_Wrapper.m_NoteClickMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_NoteClickMapActionsCallbackInterfaces.Add(instance);
            @NoteClick1.started += instance.OnNoteClick1;
            @NoteClick1.performed += instance.OnNoteClick1;
            @NoteClick1.canceled += instance.OnNoteClick1;
            @NoteClick2.started += instance.OnNoteClick2;
            @NoteClick2.performed += instance.OnNoteClick2;
            @NoteClick2.canceled += instance.OnNoteClick2;
            @NoteClick3.started += instance.OnNoteClick3;
            @NoteClick3.performed += instance.OnNoteClick3;
            @NoteClick3.canceled += instance.OnNoteClick3;
            @NoteClick4.started += instance.OnNoteClick4;
            @NoteClick4.performed += instance.OnNoteClick4;
            @NoteClick4.canceled += instance.OnNoteClick4;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="NoteClickMapActions" />
        private void UnregisterCallbacks(INoteClickMapActions instance)
        {
            @NoteClick1.started -= instance.OnNoteClick1;
            @NoteClick1.performed -= instance.OnNoteClick1;
            @NoteClick1.canceled -= instance.OnNoteClick1;
            @NoteClick2.started -= instance.OnNoteClick2;
            @NoteClick2.performed -= instance.OnNoteClick2;
            @NoteClick2.canceled -= instance.OnNoteClick2;
            @NoteClick3.started -= instance.OnNoteClick3;
            @NoteClick3.performed -= instance.OnNoteClick3;
            @NoteClick3.canceled -= instance.OnNoteClick3;
            @NoteClick4.started -= instance.OnNoteClick4;
            @NoteClick4.performed -= instance.OnNoteClick4;
            @NoteClick4.canceled -= instance.OnNoteClick4;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="NoteClickMapActions.UnregisterCallbacks(INoteClickMapActions)" />.
        /// </summary>
        /// <seealso cref="NoteClickMapActions.UnregisterCallbacks(INoteClickMapActions)" />
        public void RemoveCallbacks(INoteClickMapActions instance)
        {
            if (m_Wrapper.m_NoteClickMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="NoteClickMapActions.AddCallbacks(INoteClickMapActions)" />
        /// <seealso cref="NoteClickMapActions.RemoveCallbacks(INoteClickMapActions)" />
        /// <seealso cref="NoteClickMapActions.UnregisterCallbacks(INoteClickMapActions)" />
        public void SetCallbacks(INoteClickMapActions instance)
        {
            foreach (var item in m_Wrapper.m_NoteClickMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_NoteClickMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="NoteClickMapActions" /> instance referencing this action map.
    /// </summary>
    public NoteClickMapActions @NoteClickMap => new NoteClickMapActions(this);
    private int m_PCSchemeIndex = -1;
    /// <summary>
    /// Provides access to the input control scheme.
    /// </summary>
    /// <seealso cref="UnityEngine.InputSystem.InputControlScheme" />
    public InputControlScheme PCScheme
    {
        get
        {
            if (m_PCSchemeIndex == -1) m_PCSchemeIndex = asset.FindControlSchemeIndex("PC");
            return asset.controlSchemes[m_PCSchemeIndex];
        }
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "NoteClickMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="NoteClickMapActions.AddCallbacks(INoteClickMapActions)" />
    /// <seealso cref="NoteClickMapActions.RemoveCallbacks(INoteClickMapActions)" />
    public interface INoteClickMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "NoteClick1" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNoteClick1(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NoteClick2" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNoteClick2(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NoteClick3" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNoteClick3(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "NoteClick4" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnNoteClick4(InputAction.CallbackContext context);
    }
}
